### ISSUE TITLE
Define a map structure for upstream configuration

### ISSUE THREAD

**Issue by cyakimov** [cyakimov/helios#5]
Proposed structure:

```yaml
----
upstreams:
  - name: httpbin
    connect_timeout: 5s
    host: httpbin.org
    port: 443
    tls:
     sni: httpbin.org

routes:
  - host: foo.bar.com
    http:
      paths:
        - path: /foo
          upstream: httpbin
```
